// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace eShop.DatabaseRepository.DbModels
{
    public partial class Categories
    {
        public Categories()
        {
            ProductsInCategories = new HashSet<ProductsInCategories>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ProductsInCategories> ProductsInCategories { get; set; }
    }
}